using System;
using System.Text;

namespace KF.OData.Generators;

/// <summary>
/// Emits the C# source for a generated OData controller.
/// </summary>
internal static class ControllerEmitter
{
    public static string Emit(DbContextInfo context, EntitySetInfo entity)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using KF.OData.Controllers;");
        sb.AppendLine("using KF.OData.Security;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.OData.Routing.Controllers;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();

        var generatedNamespace = $"{context.ContextNamespace}.Controllers";
        sb.AppendLine($"namespace {generatedNamespace};");
        sb.AppendLine();

        var schemaPrefix = entity.Schema?.Replace(".", "") ?? "";
        var controllerName = $"{schemaPrefix}{entity.EntityTypeName}Controller";
        var routeSegment = entity.Schema is not null
            ? $"{context.ContextPrefix}/{entity.Schema}"
            : context.ContextPrefix;

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Auto-generated OData controller for <see cref=\"{entity.EntityTypeFullName}\"/>.");
        sb.AppendLine($"/// Provides full CRUD via /odata/{routeSegment}/{entity.PropertyName}.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public partial class {controllerName} : KoreForgeODataController<{context.ContextTypeFullName}, {entity.EntityTypeFullName}, {entity.KeyTypeName ?? "int"}>");
        sb.AppendLine("{");

        // Constructor
        sb.AppendLine($"    public {controllerName}(");
        sb.AppendLine($"        {context.ContextTypeFullName} context,");
        sb.AppendLine($"        IAuthorizationService authorizationService,");
        sb.AppendLine($"        IRowLevelFilterProvider<{entity.EntityTypeFullName}>? rowFilter = null)");
        sb.AppendLine($"        : base(context, authorizationService, rowFilter)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();

        // EntitySet override
        sb.AppendLine($"    protected override DbSet<{entity.EntityTypeFullName}> EntitySet => DbContext.{entity.PropertyName};");
        sb.AppendLine();

        // GetKey override
        if (entity.KeyPropertyName is not null)
        {
            sb.AppendLine($"    protected override {entity.KeyTypeName} GetKey({entity.EntityTypeFullName} entity) => entity.{entity.KeyPropertyName};");
            sb.AppendLine();

            // FindByKeyAsync
            sb.AppendLine($"    protected override Task<{entity.EntityTypeFullName}?> FindByKeyAsync({entity.KeyTypeName} key, CancellationToken ct)");
            sb.AppendLine($"        => DbContext.{entity.PropertyName}.FindAsync(new object[] {{ key }}, ct).AsTask();");
            sb.AppendLine();

            // BuildKeyPredicate
            sb.AppendLine($"    protected override Expression<Func<{entity.EntityTypeFullName}, bool>> BuildKeyPredicate({entity.KeyTypeName} key)");
            sb.AppendLine($"        => e => e.{entity.KeyPropertyName}!.Equals(key);");
        }
        else
        {
            // Fallback for entities without detected key — emit a diagnostic-friendly stub
            sb.AppendLine($"    // WARNING: No primary key detected for {entity.EntityTypeName}. Override these methods manually.");
            sb.AppendLine($"    protected override int GetKey({entity.EntityTypeFullName} entity) => throw new NotSupportedException(\"No primary key detected.\");");
            sb.AppendLine();
            sb.AppendLine($"    protected override Task<{entity.EntityTypeFullName}?> FindByKeyAsync(int key, CancellationToken ct)");
            sb.AppendLine($"        => throw new NotSupportedException(\"No primary key detected.\");");
            sb.AppendLine();
            sb.AppendLine($"    protected override Expression<Func<{entity.EntityTypeFullName}, bool>> BuildKeyPredicate(int key)");
            sb.AppendLine($"        => throw new NotSupportedException(\"No primary key detected.\");");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
