using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace KF.OData.Generators;

/// <summary>
/// Emits the C# source for a generated IEdmModelConfigurator that registers entity sets.
/// </summary>
internal static class EdmConfiguratorEmitter
{
    public static string Emit(DbContextInfo context)
    {
        var eligibleSets = context.EntitySets.Where(e => !e.IsIgnored).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using KF.OData.Configuration;");
        sb.AppendLine("using Microsoft.OData.ModelBuilder;");
        sb.AppendLine();

        var generatedNamespace = $"{context.ContextNamespace}.Generated.Configuration";
        sb.AppendLine($"namespace {generatedNamespace};");
        sb.AppendLine();

        var className = $"{context.ContextPrefix}EdmConfigurator";

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Auto-generated EDM model configurator for {context.ContextTypeName}.");
        sb.AppendLine($"/// Registers entity sets at route prefix /odata/{context.ContextPrefix}/.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {className} : IEdmModelConfigurator");
        sb.AppendLine("{");
        sb.AppendLine($"    public string ContextPrefix => \"{context.ContextPrefix}\";");
        sb.AppendLine();
        sb.AppendLine("    public void Configure(ODataConventionModelBuilder builder)");
        sb.AppendLine("    {");

        foreach (var entity in eligibleSets)
        {
            sb.AppendLine($"        builder.EntitySet<{entity.EntityTypeFullName}>(\"{entity.PropertyName}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
