using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace KF.OData.Generators;

/// <summary>
/// Roslyn source generator that reads [assembly: GenerateODataFor(typeof(TContext))] attributes
/// and generates OData CRUD controllers per non-ignored DbSet entity, plus IEdmModelConfigurator
/// per schema group within each DbContext.
/// </summary>
[Generator]
public sealed class ODataSourceGenerator : ISourceGenerator
{
    private const string AttributeSource = @"// <auto-generated />
#nullable enable

namespace KF.OData.Attributes
{
    /// <summary>
    /// Marks a DbContext type for OData controller generation.
    /// Apply as an assembly attribute: [assembly: GenerateODataFor(typeof(MyDbContext))]
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class GenerateODataForAttribute : System.Attribute
    {
        public GenerateODataForAttribute(System.Type contextType) => ContextType = contextType;
        public System.Type ContextType { get; }
    }
}
";

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new DbContextReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // Always inject the marker attribute so consumers can reference it
        context.AddSource("GenerateODataForAttribute.g.cs", AttributeSource);

        if (context.SyntaxReceiver is not DbContextReceiver receiver || receiver.CandidateAttributes.Count == 0)
            return;

        var compilation = context.Compilation;

        foreach (var attributeSyntax in receiver.CandidateAttributes)
        {
            if (attributeSyntax.ArgumentList?.Arguments.Count != 1)
                continue;

            if (attributeSyntax.ArgumentList.Arguments[0].Expression is not TypeOfExpressionSyntax typeOfExpr)
                continue;

            var semanticModel = compilation.GetSemanticModel(attributeSyntax.SyntaxTree);
            var typeInfo = semanticModel.GetTypeInfo(typeOfExpr.Type);
            if (typeInfo.Type is not INamedTypeSymbol contextSymbol)
                continue;

            var contextInfo = DbContextAnalyzer.TryExtract(contextSymbol, compilation);
            if (contextInfo is null)
                continue;

            var nonIgnored = contextInfo.EntitySets.Where(e => !e.IsIgnored).ToList();

            // Generate one controller per non-ignored entity
            foreach (var entity in nonIgnored)
            {
                if (entity.KeyPropertyName is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "KFODATA001",
                            "No primary key detected",
                            "Entity '{0}' has no detectable primary key. Generated controller will throw at runtime.",
                            "KoreForge.OData",
                            DiagnosticSeverity.Warning,
                            isEnabledByDefault: true),
                        attributeSyntax.GetLocation(),
                        entity.EntityTypeName));
                }

                var controllerSource = ControllerEmitter.Emit(contextInfo, entity);
                context.AddSource($"{entity.EntityTypeName}Controller.g.cs", controllerSource);
            }

            // Group entities by schema, emit one EDM configurator per group
            var schemaGroups = nonIgnored.GroupBy(e => e.Schema);
            foreach (var group in schemaGroups)
            {
                var edmSource = EdmConfiguratorEmitter.Emit(contextInfo, group.Key, group.ToList());
                var configName = group.Key is not null
                    ? $"{contextInfo.ContextPrefix}{group.Key}EdmConfigurator"
                    : $"{contextInfo.ContextPrefix}EdmConfigurator";
                context.AddSource($"{configName}.g.cs", edmSource);
            }
        }
    }
}
